# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 618301c17ced48fede1dcd9cb041e61ea4449f20235b3ec051300fe5a2e75d0fa388f86a7631506e3bbacd5d86e16b2e12986f54359bb274c6bfa3f1c999467a

test:
  secret_key_base: ab078019ea0c83a234837e2214a3f3d1b0c074a1d7248ddfda194701ede87d18b7e5cb657f9ff437fd5f992de26126fb914972e63da6855d05a6a8ef8e24e1e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
